name: CI - Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: mysecretpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Docker Compose  # 🛠️ Add this step before testing
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be available..."
          sleep 15  # Extended wait time

      - name: Run tests
        run: make test
